fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.1.0
    concat:
      repo: git://github.com/theforeman/puppet-concat.git
      ref: 1.3.1
  symlinks:
    edac: "#{source_dir}"
